-- MySQL Script generated by MySQL Workbench
-- Sat Sep 19 15:24:24 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering


use atacadao;


-- -----------------------------------------------------
-- Table `perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pc_perfil` (
  `idperfil` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idperfil`),
  UNIQUE INDEX `idperfil_UNIQUE` (`idperfil` ASC) )
ENGINE = InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;


-- -----------------------------------------------------
-- Table `colaboradores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pc_usuarios` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `matricula` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `login` VARCHAR(20) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `id_perfil` INT NOT NULL,
  PRIMARY KEY (`idusuario`),
  UNIQUE INDEX `idusuario_UNIQUE` (`idusuario` ASC) ,
  UNIQUE INDEX `matricula_UNIQUE` (`matricula` ASC) ,
  UNIQUE INDEX `login_UNIQUE` (`login` ASC) ,
  INDEX `fk_colaborador_perfil_idx` (`id_perfil` ASC) ,
  CONSTRAINT `fk_colaborador_perfil`
    FOREIGN KEY (`id_perfil`)
    REFERENCES `pc_perfil` (`idperfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;


-- -----------------------------------------------------
-- Table `status_balancas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pc_status_balancas` (
  `idstatusBalanca` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idstatusBalanca`),
  UNIQUE INDEX `idstatus_balanca_UNIQUE` (`idstatusBalanca` ASC) )
ENGINE = InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;


-- -----------------------------------------------------
-- Table `balancas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pc_balancas` (
  `idbalanca` INT NOT NULL AUTO_INCREMENT,
  `numBalanca` INT NOT NULL,
  `pip` INT,
  `setor` VARCHAR(45) NOT NULL,
  `numSerie` INT UNSIGNED NOT NULL,
  `localAtual` VARCHAR(60) NOT NULL,
  `id_status_balanca` INT NOT NULL,
  PRIMARY KEY (`idbalanca`),
  UNIQUE INDEX `idbalanca_UNIQUE` (`idbalanca` ASC) ,
  UNIQUE INDEX `numBalanca_UNIQUE` (`numBalanca` ASC) ,
  INDEX `fk_balanca_status_balanca1_idx` (`id_status_balanca` ASC) ,
  CONSTRAINT `fk_balanca_status_balanca1`
    FOREIGN KEY (`id_status_balanca`)
    REFERENCES `pc_status_balancas` (`idstatusBalanca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;


-- -----------------------------------------------------
-- Table `prestadores_servico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pc_prestadores_servico` (
  `idprestador` INT NOT NULL AUTO_INCREMENT,
  `cnpj` VARCHAR(14) NOT NULL,
  `razaoSocial` VARCHAR(60) NOT NULL,
  `telefone` VARCHAR(14) NOT NULL,
  `email` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`idprestador`),
  UNIQUE INDEX `cnpj_UNIQUE` (`cnpj` ASC) )
ENGINE = InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;


-- -----------------------------------------------------
-- Table `status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pc_status` (
  `idstatus` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idstatus`),
  UNIQUE INDEX `idstatus_UNIQUE` (`idstatus` ASC) )
ENGINE = InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;


-- -----------------------------------------------------
-- Table `atendimentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pc_atendimentos` (
  `idatendimento` INT NOT NULL AUTO_INCREMENT,
  `dataInicioAtendimento` DATE NOT NULL,
  `dataFimAtendimento` DATE NULL,
  `id_prestador_servico` INT NOT NULL,
  `id_usuario` INT NOT NULL,
  `id_status` INT NOT NULL,
  UNIQUE INDEX `idatendimento_UNIQUE` (`idatendimento` ASC) ,
  PRIMARY KEY (`idatendimento`),
  INDEX `fk_atendimento_prestador_servico1_idx` (`id_prestador_servico` ASC) ,
  INDEX `fk_atendimento_colaborador1_idx` (`id_usuario` ASC) ,
  INDEX `fk_atendimento_status1_idx` (`id_status` ASC) ,
  CONSTRAINT `fk_atendimento_prestador_servico1`
    FOREIGN KEY (`id_prestador_servico`)
    REFERENCES `pc_prestadores_servico` (`idprestador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_atendimento_colaborador1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `pc_usuarios` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_atendimento_status1`
    FOREIGN KEY (`id_status`)
    REFERENCES `pc_status` (`idstatus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;


-- -----------------------------------------------------
-- Table `ordens_servico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pc_ordens_servico` (
  `idordemServico` INT NOT NULL AUTO_INCREMENT,
  `numOrdemServico` INT NOT NULL,
  `valor` DECIMAL(10) NULL,
  PRIMARY KEY (`idordemServico`),
  UNIQUE INDEX `idordemServico_UNIQUE` (`idordemServico` ASC) ,
  UNIQUE INDEX `numOrdemServico_UNIQUE` (`numOrdemServico` ASC) )
ENGINE = InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

-- -----------------------------------------------------
-- Table `reparos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pc_reparos` (
  `idreparo` INT NOT NULL AUTO_INCREMENT,
  `descDefeito` VARCHAR(200) NOT NULL,
  `dataInicioReparo` DATE NOT NULL,
  `dataFimReparo` DATE NULL,
  `observacao` VARCHAR(80) NULL,
  `id_atendimento` INT NOT NULL,
  `id_balanca` INT NOT NULL,
  `id_ordem_servico` INT NOT NULL,
  `id_status` INT NOT NULL,
  PRIMARY KEY (`idreparo`),
  UNIQUE INDEX `idreparo_UNIQUE` (`idreparo` ASC) ,
  INDEX `fk_reparo_atendimento1_idx` (`id_atendimento` ASC) ,
  INDEX `fk_reparo_balanca1_idx` (`id_balanca` ASC) ,
  INDEX `fk_reparo_ordem_servico1_idx` (`id_ordem_servico` ASC) ,
  INDEX `fk_reparo_status1_idx` (`id_status` ASC) ,
  CONSTRAINT `fk_reparo_atendimento1`
    FOREIGN KEY (`id_atendimento`)
    REFERENCES `pc_atendimentos` (`idatendimento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reparo_balanca1`
    FOREIGN KEY (`id_balanca`)
    REFERENCES `pc_balancas` (`idbalanca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reparo_ordem_servico1`
    FOREIGN KEY (`id_ordem_servico`)
    REFERENCES `pc_ordens_servico` (`idordemServico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reparo_status1`
    FOREIGN KEY (`id_status`)
    REFERENCES `pc_status` (`idstatus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

-- -----------------------------------------------------
-- INSERÇAO
-- -----------------------------------------------------

-- INSERT INTO pc_status (descricao) VALUES ("ABERTO");
-- INSERT INTO pc_status (descricao) VALUES ("EM ATENDIMENTO");
-- INSERT INTO pc_status (descricao) VALUES ("CONCLUIDO");
-- 
-- INSERT INTO pc_ordens_servico (numOrdemServico, valor) VALUES (1,5000);
-- 
-- INSERT INTO pc_status_balancas (descricao) VALUES ("FUNCIONANDO");
-- INSERT INTO pc_status_balancas (descricao) VALUES ("ESTRAGADA");
-- 
-- INSERT INTO pc_perfil (descricao) VALUES ("CPD");

INSERT INTO `pc_usuarios`(`matricula`, `nome`, `login`, `senha`, `id_perfil`) VALUES (99999,'admin','admin','21232f297a57a5a743894a0e4a801fc3',1);